apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
<<<<<<< HEAD
        image: vvkmulukutla03/custom-flask-application-server:19
=======
        image: vvkmulukutla03/custom-flask-application-server:19
>>>>>>> 990f62908a0b66d0a6e6fd7d3276ac6553cf0034
        ports:
        - containerPort: 6969